- name: Add Erlang Solutions key
  apt_key: url=http://packages.erlang-solutions.com/debian/erlang_solutions.asc state=present
- name: Add Erlang Solutions repo
  apt_repository: repo='deb http://packages.erlang-solutions.com/debian wheezy contrib' state=present
- name: Install build tools
  apt: pkg={{item}} state=installed
  with_items:
    - erlang-base=1:16.b.3-3
    - erlang-diameter=1:16.b.3-3
    - erlang-eldap=1:16.b.3-3
    - erlang-ic-java=1:16.b.3-3
    - erlang-src=1:16.b.3-3
    - erlang-examples=1:16.b.3-3
    - erlang-runtime-tools=1:16.b.3-3
    - erlang-ssl=1:16.b.3-3
    - erlang-syntax-tools=1:16.b.3-3
    - erlang-asn1=1:16.b.3-3
    - erlang-ic=1:16.b.3-3
    - erlang-mnesia=1:16.b.3-3
    - erlang-crypto=1:16.b.3-3
    - erlang-public-key=1:16.b.3-3
    - erlang=1:16.b.3-3
    - git
    - build-essential
- name: Copy rebar
  copy: src=rebar dest=/usr/bin/rebar mode=0755
