- name: Add Erlang Solutions key
  apt_key: url=http://packages.erlang-solutions.com/debian/erlang_solutions.asc state=present
- name: Add Erlang Solutions repo
  apt_repository: repo='deb http://packages.erlang-solutions.com/debian wheezy contrib' state=present
- name: Install build tools
  apt: pkg={{item}} state=installed
  with_items:
    - erlang
    - git
    - build-essential
- name: Copy rebar
  copy: src=rebar dest=/usr/bin/rebar mode=0755
